---
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'build',
      '--tag=asia.gcr.io/${PROJECT_ID}/my-project:0.1.0-strapi-3.6.8',
      '-f', 'compose/production/my-project/Dockerfile.cloudrun', '.'
    ]
    env:
      - PROJECT_ID=int-ml-ai

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/${PROJECT_ID}/my-project:0.1.0-strapi-3.6.8']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-project'
      - '--image'
      - 'asia.gcr.io/${PROJECT_ID}/my-project:0.1.0-strapi-3.6.8'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1000m'
      - '--concurrency'
      - '80'
      - '--timeout=300'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
    env:
      - PROJECT_ID=int-ml-ai

images:
- "asia.gcr.io/${PROJECT_ID}/my-project:0.1.0-strapi-3.6.8"

# options:
#   logging: CLOUD_LOGGING_ONLY